// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTickets.Api.Database;

#nullable disable

namespace PTickets.Api.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    [Migration("20260804173002_MoveScheduleToStreet")]
    partial class MoveScheduleToStreet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PTickets.Api.Inspections.Data.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConductedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StreetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("PTickets.Api.Inspectors.Data.Inspector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inspectors");
                });

            modelBuilder.Entity("PTickets.Api.Penalties.Data.Penalty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Street", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RepresentsWholeZone")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Streets", (string)null);
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("PTickets.Api.Inspections.Data.Inspection", b =>
                {
                    b.OwnsOne("PTickets.Api.Inspections.Data.TicketCheckResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("InspectionId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsValid")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Result_IsValid");

                            b1.Property<string>("TicketProviderMessage")
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_Message");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_ValidFrom");

                            b1.Property<DateTime?>("ValidTo")
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_ValidTo");

                            b1.HasKey("InspectionId");

                            b1.ToTable("Inspections");

                            b1.WithOwner()
                                .HasForeignKey("InspectionId");
                        });

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("Street", b =>
                {
                    b.HasOne("Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PTickets.Api.Zones.Data.PaidParkingSchedule", "PaidParkingSchedule", b1 =>
                        {
                            b1.Property<Guid>("StreetId")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidParkingSchedule_EndTime");

                            b1.Property<string>("PaidDays")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidParkingSchedule_PaidDays");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidParkingSchedule_StartTime");

                            b1.HasKey("StreetId");

                            b1.ToTable("Streets");

                            b1.WithOwner()
                                .HasForeignKey("StreetId");
                        });

                    b.Navigation("PaidParkingSchedule");
                });
#pragma warning restore 612, 618
        }
    }
}
