// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTickets.Api.Database;

#nullable disable

namespace PTickets.Api.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    partial class ParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PTickets.Api.Inspections.Data.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConductedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decision")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StreetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("PTickets.Api.Inspectors.Data.Inspector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inspectors");
                });

            modelBuilder.Entity("PTickets.Api.Penalties.Data.Penalty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Penalties");
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("PTickets.Api.Inspections.Data.Inspection", b =>
                {
                    b.OwnsOne("PTickets.Api.Inspections.Data.TicketCheckResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("InspectionId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsValid")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Result_IsValid");

                            b1.Property<string>("TicketProviderMessage")
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_Message");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_ValidFrom");

                            b1.Property<DateTime?>("ValidTo")
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_ValidTo");

                            b1.HasKey("InspectionId");

                            b1.ToTable("Inspections");

                            b1.WithOwner()
                                .HasForeignKey("InspectionId");
                        });

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("Zone", b =>
                {
                    b.OwnsOne("PTickets.Api.Zones.Data.PaidParkingSchedule", "PaidParkingSchedule", b1 =>
                        {
                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("TEXT");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidParkingSchedule_EndTime");

                            b1.Property<string>("PaidDays")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidParkingSchedule_PaidDays");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidParkingSchedule_StartTime");

                            b1.HasKey("ZoneId");

                            b1.ToTable("Zones");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");
                        });

                    b.OwnsMany("PTickets.Api.Zones.Data.Street", "Streets", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("ZoneId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ZoneId");

                            b1.ToTable("Street");

                            b1.WithOwner()
                                .HasForeignKey("ZoneId");
                        });

                    b.Navigation("PaidParkingSchedule");

                    b.Navigation("Streets");
                });
#pragma warning restore 612, 618
        }
    }
}
