// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTickets.Modules.Inspections.Infrastructure.Persistence;

#nullable disable

namespace PTickets.Modules.Inspections.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InspectionsDbContext))]
    [Migration("20260924211427_ZoneAndStreetOnlyInspection")]
    partial class ZoneAndStreetOnlyInspection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inspections")
                .HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PTickets.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("NoticeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PhotoIds");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inspections", "inspections");
                });

            modelBuilder.Entity("PTickets.Modules.Inspections.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions", "inspections");
                });

            modelBuilder.Entity("PTickets.Modules.Inspections.Domain.ViolationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ViolationTypeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("ViolationEntries", "inspections");
                });

            modelBuilder.Entity("PTickets.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.OwnsOne("PTickets.Shared.ValueObjects.TicketCheckResult", "SecondCheckResult", b1 =>
                        {
                            b1.Property<Guid>("InspectionId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsValid")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SecondCheckIsValid");

                            b1.Property<string>("ProviderMessage")
                                .HasColumnType("TEXT")
                                .HasColumnName("SecondCheckProviderMessage");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("TEXT")
                                .HasColumnName("SecondCheckValidFrom");

                            b1.Property<DateTime?>("ValidTo")
                                .HasColumnType("TEXT")
                                .HasColumnName("SecondCheckValidTo");

                            b1.HasKey("InspectionId");

                            b1.ToTable("Inspections", "inspections");

                            b1.WithOwner()
                                .HasForeignKey("InspectionId");
                        });

                    b.OwnsOne("PTickets.Shared.ValueObjects.TicketCheckResult", "TicketResult", b1 =>
                        {
                            b1.Property<Guid>("InspectionId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsValid")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TicketIsValid");

                            b1.Property<string>("ProviderMessage")
                                .HasColumnType("TEXT")
                                .HasColumnName("TicketProviderMessage");

                            b1.Property<DateTime?>("ValidFrom")
                                .HasColumnType("TEXT")
                                .HasColumnName("TicketValidFrom");

                            b1.Property<DateTime?>("ValidTo")
                                .HasColumnType("TEXT")
                                .HasColumnName("TicketValidTo");

                            b1.HasKey("InspectionId");

                            b1.ToTable("Inspections", "inspections");

                            b1.WithOwner()
                                .HasForeignKey("InspectionId");
                        });

                    b.Navigation("SecondCheckResult");

                    b.Navigation("TicketResult");
                });

            modelBuilder.Entity("PTickets.Modules.Inspections.Domain.ViolationEntry", b =>
                {
                    b.HasOne("PTickets.Modules.Inspections.Domain.Inspection", null)
                        .WithMany("Violations")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PTickets.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
