// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PTickets.Modules.Tickets.Infrastructure.Persistence;

#nullable disable

namespace PTickets.Modules.Tickets.Infrastructure.Migrations
{
    [DbContext(typeof(TicketsDbContext))]
    [Migration("20260929152237_AddExternalTicketFields")]
    partial class AddExternalTicketFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PTickets.Modules.Tickets.Domain.ResidentCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StreetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber", "StreetId", "ValidTo");

                    b.ToTable("ResidentCards", "tickets");
                });

            modelBuilder.Entity("PTickets.Modules.Tickets.Domain.StreetZoneMapping", b =>
                {
                    b.Property<Guid>("StreetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("TEXT");

                    b.HasKey("StreetId");

                    b.ToTable("StreetZoneMappings", "tickets");
                });

            modelBuilder.Entity("PTickets.Modules.Tickets.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTicketId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkingZone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StreetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTicketId")
                        .IsUnique();

                    b.HasIndex("RegistrationNumber", "StreetId", "ValidTo");

                    b.ToTable("Tickets", "tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
